version: '3.2'

services:

  ch-master:
    container_name: ch_master
    image: yandex/clickhouse-server
    depends_on:
      - ch-sub-1
      - ch-sub-2
      - ch-sub-3
    ports:
      - 9000:9000
      - 8123:8123
    volumes:
      - './data/clickhouse:/var/lib'

  ch-sub-1:
    container_name: ch_sub_1
    image: yandex/clickhouse-server
    ports:
      - 9001:9000
      - 8124:8123
    volumes:
      - './data/clickhouse:/var/lib'


  ch-sub-2:
    container_name: ch_sub_2
    image: yandex/clickhouse-server
    ports:
      - 9002:9000
      - 8125:8123
    volumes:
      - './data/clickhouse:/var/lib'
  
  ch-sub-3:
    container_name: ch_sub_3
    image: yandex/clickhouse-server
    ports:
      - 9003:9000
      - 8126:8123
    volumes:
      - './data/clickhouse:/var/lib'
